---
- hosts: all
  remote_user: '{{ remote_user }}'
  become: yes
  become_user: root
  vars:
    remote_user: lighthouse
    distribution_dest: '/var/www/lighthouse-web/dist'
    nginx_sites:
      - default
      - lighthouse.pm
    apt_php_packages:
      - php7.0
      - php7.0-cgi
      - php7.0-cli
      - php7.0-common
      - php7.0-curl
      - php7.0-fpm
      - php7.0-gd
      - php7.0-intl
      - php7.0-json
      - php7.0-mysql
      - php7.0-mbstring
      - php7.0-xml
      - php7.0-zip
  pre_tasks:
    - name: Creating user nginx
      user: name=nginx system=yes createhome=no shell=/usr/sbin/nologin
  roles:
    - { role: geerlingguy.nginx, nginx_user: nginx }
  tasks:
    - name: Copy distribution
      copy: src='../dist/' dest={{ distribution_dest }}
    - name: Set user and group for distro
      file: dest={{ distribution_dest }} owner={{ remote_user }} group={{ remote_user }} recurse=true
    - name: Copy Nginx sites
      copy: src='../deploy/nginx/sites/{{ item }}' dest='/etc/nginx/sites-available/{{ item }}'
      with_items: '{{ nginx_sites }}'
    - name: Register sites with Nginx
      file: src='/etc/nginx/sites-available/{{ item }}' dest='/etc/nginx/sites-enabled/{{ item }}' state=link
      with_items: '{{ nginx_sites }}'
    - name: Restart Nginx
      service: name=nginx state=restarted
